# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8b9185ef737dd96fe4aff87a7a826d6b085e5892c37761ae19d25986dc3e8c9b6515774f6d02ebb5cc52d3db3dee7f88f63a777db0a2491f46b270288708405

test:
  secret_key_base: e9aff03dda8f9d2febcd9f588f45a874cae7089cdc291b97b710fd917a7fd0db0ba5977429c941641a483ea354d3e1997ab56c90c5f3b3cc3ec188bcd74751bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
